import mongoose from 'mongoose';

const { Schema, model } = mongoose;

// Live Notification Schema
const LiveNotificationSchema = new Schema({
  message: { type: String, required: true },
  type: { type: String, enum: ["info", "success", "warning", "announcement"], default: "info" },
  link: String,
  active: { type: Boolean, default: false },
  startDate: Date,
  endDate: Date,
}, { timestamps: true });


// Site Data Schema - stores all site configuration
const SiteDataSchema = new Schema({
  intro: {
    enabled: { type: Boolean, default: true },
    videoUrl: { type: String, default: '/intro.mp4' },
    posterUrl: { type: String, default: '' },
    autoplay: { type: Boolean, default: true },
    loop: { type: Boolean, default: true }
  },
  home: {
    hero: {
      title: String,
      subtitle: String,
      videoUrl: String,
      cta1: String,
      cta2: String
    },
    whatWeDo: [{
      id: String,
      title: String,
      description: String,
      icon: String
    }],
    vision: {
      title: String,
      text: String
    },
    partners: [{
      id: String,
      name: String,
      logoUrl: String
    }]
  },
  about: {
    story: {
      title: String,
      text: String
    },
    team: [{
      id: String,
      name: String,
      role: String,
      bio: String,
      photoUrl: String,
      linkedin: String,
      github: String
    }],
    values: [{
      id: String,
      title: String,
      description: String
    }]
  },
  contact: {
    message: String,
    email: String,
    discord: String,
    location: String,

    socials: {
      facebook: { type: String, default: 'https://facebook.com' },
      twitter: { type: String, default: 'https://twitter.com' },
      instagram: { type: String, default: 'https://instagram.com' },
      linkedin: { type: String, default: 'https://linkedin.com' },
      discord: String,
      github: String,
      youtube: String
    },
    faq: [{
      id: String,
      question: String,
      answer: String
    }]
  },
  join: {
    hero: {
      title: String,
      subtitle: String
    },
    whyJoinUs: [{
      id: String,
      title: String,
      description: String
    }],
    positions: [{
      id: String,
      title: String,
      description: String,
      requirements: String
    }]
  },
  statistics: [{
    id: String,
    icon: String,
    value: Number,
    suffix: String,
    label: String,
    color: String
  }],
  testimonials: [{
    id: String,
    name: String,
    role: String,
    image: String,
    rating: Number,
    text: String
  }],
  technologies: [{
    id: String,
    category: String,
    icon: String,
    items: [String]
  }],
  blog: [{
    id: String,
    title: String,
    excerpt: String,
    content: String,
    image: String,
    mediaGallery: [{
      type: { type: String, enum: ['image', 'video'] },
      url: String,
      caption: String
    }],
    author: String,
    date: String,
    category: String,
    tags: [String]
  }],
  seo: {
    home: { title: String, description: String, ogImage: String },
    projects: { title: String, description: String, ogImage: String },
    about: { title: String, description: String, ogImage: String },
    contact: { title: String, description: String, ogImage: String },
    join: { title: String, description: String, ogImage: String }
  },
  chatbot: {
    enabled: { type: Boolean, default: true },
    name: { type: String, default: 'Tec' },
    welcomeMessage: { type: String, default: 'مرحباً! أنا Tec 🤖، مساعدك الذكي في جامعة عمان العربية. كيف يمكنني مساعدتك اليوم؟' }
  }
}, { timestamps: true });

// Project Schema
const ProjectSchema = new Schema({
  title: { type: String, required: true },
  type: { type: String, required: true },
  tags: [String],
  description: String,
  thumbnailUrl: String,
  coverUrl: String,
  features: [String],
  technologies: [String],
  releaseDate: String,
  platforms: [String],
  gallery: [String],
  mediaGallery: [{ url: { type: String, required: true }, caption: String }],
  downloadLink: String,
  videoLink: String,
  // Rating system
  ratings: {
    total: { type: Number, default: 0 },
    count: { type: Number, default: 0 },
    average: { type: Number, default: 0 },
    breakdown: {
      1: { type: Number, default: 0 },
      2: { type: Number, default: 0 },
      3: { type: Number, default: 0 },
      4: { type: Number, default: 0 },
      5: { type: Number, default: 0 }
    }
  }
}, { timestamps: true });

// Message Schema
const MessageSchema = new Schema({
  name: { type: String, required: true },
  email: { type: String, required: true },
  message: { type: String, required: true },
  date: { type: Date, default: Date.now }
}, { timestamps: true });

// Application Schema
const ApplicationSchema = new Schema({
  name: { type: String, required: true },
  email: { type: String, required: true },
  position: { type: String, required: true },
  portfolio: String,
  message: String,
  date: { type: Date, default: Date.now }
}, { timestamps: true });

// Project Submission Schema
const ProjectSubmissionSchema = new Schema({
  name: { type: String, required: true },
  email: { type: String, required: true },
  projectName: { type: String, required: true },
  description: String,
  links: [String],
  date: { type: Date, default: Date.now }
}, { timestamps: true });

// User Schema - With Role-Based Access Control (RBAC)
const UserSchema = new Schema({
  username: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  role: { 
    type: String, 
    enum: ['super_admin', 'limited_admin', 'editor', 'viewer'], 
    default: 'viewer' 
  },
  isActive: { type: Boolean, default: true },
  lastLogin: { type: Date, default: null },
  permissions: {
    dashboard: { type: Boolean, default: false },
    home_content: { type: Boolean, default: false },
    about_content: { type: Boolean, default: false },
    projects: { type: Boolean, default: false },
    blog: { type: Boolean, default: false },
    technologies: { type: Boolean, default: false },
    user_management: { type: Boolean, default: false },
    chatbot_conversations: { type: Boolean, default: false },
    chatbot_settings: { type: Boolean, default: false },
    statistics: { type: Boolean, default: false },
    visitors: { type: Boolean, default: false },
    ratings: { type: Boolean, default: false },
    testimonials: { type: Boolean, default: false },
    testimonial_submissions: { type: Boolean, default: false },
    messages: { type: Boolean, default: false },
    project_submissions: { type: Boolean, default: false },
    contact_settings: { type: Boolean, default: false },
    general_settings: { type: Boolean, default: false }
  }
}, { timestamps: true });

// Visitor Schema - Track all visitor information
const VisitorSchema = new Schema({
  ip: String,
  country: String,
  countryCode: String,
  region: String,
  city: String,
  latitude: Number,
  longitude: Number,
  timezone: String,
  isp: String,
  browser: String,
  browserVersion: String,
  os: String,
  osVersion: String,
  device: String,
  deviceType: String,
  screenResolution: String,
  language: String,
  languages: [String],
  page: String,
  referrer: String,
  userAgent: String,
  visitTime: { type: Date, default: Date.now },
  sessionDuration: Number,
  isBot: Boolean,
  isMobile: Boolean,
  isTablet: Boolean,  isDesktop: Boolean,
  connectionType: String,
  effectiveType: String,
  rtt: Number,
  downlink: Number,
  cpuCores: Number,
  deviceMemory: Number,
  batteryLevel: Number,
  batteryCharging: Boolean,
  webglVendor: String,
  webglRenderer: String,
  plugins: [String],
  postalCode: String,
  regionCode: String,
  localTime: String,
  timeZoneOffset: Number,
  pagesVisited: [String],
  scrollDepth: Number,
  utmSource: String,
  utmMedium: String,
  utmCampaign: String,
  utmTerm: String,
  utmContent: String,
  sessionId: String,
  isReturningVisitor: Boolean,
  initialReferrer: String,
  screenOrientation: String,
  touchSupport: Boolean,
  hardwareConcurrency: Number,
  javaEnabled: Boolean,
  doNotTrack: Boolean,
  adBlocker: Boolean,
  viewportWidth: Number,
  viewportHeight: Number,
  pixelRatio: Number,
  colorDepth: Number,
  cookiesEnabled: Boolean,
  localStorageEnabled: Boolean,
  sessionStorageEnabled: Boolean,
  webSocketEnabled: Boolean,
  webRTCEnabled: Boolean,
  canvasFingerprint: String,
  audioFingerprint: String,
  fontFingerprint: String,
  timezoneOffset: Number,
  timezoneName: String,
  networkSpeed: String,
  connectionEffectiveType: String,
  connectionRtt: Number,
  connectionDownlink: Number,
  connectionSaveData: Boolean,
  cpuLogicalCores: Number,
  deviceMemoryGb: Number,
  batteryStatusCharging: Boolean,
  batteryStatusLevel: Number,
  batteryStatusChargingTime: Number,
  batteryStatusDischargingTime: Number,
  gpuVendor: String,
  gpuRenderer: String,
  pluginsList: [String],
  screenOrientationType: String,
  screenOrientationAngle: Number,
  maxTouchPoints: Number,
  platform: String,
  product: String,
  vendor: String,
  vendorSub: String,
  productSub: String,
  buildID: String,
  oscpu: String,
  appCodeName: String,
  appName: String,
  appVersion: String,
  languageList: [String],
  hardwareConcurrencyCount: Number,
  devicePixelRatio: Number,
  maxTouchPointsCount: Number,
  memoryUsed: Number,
  memoryTotal: Number,
  memoryLimit: Number,
  memoryJsHeapSizeLimit: Number,
  memoryJsHeapSizeUsed: Number,
  memoryJsHeapSizeTotal: Number,
  memoryDeviceMemory: Number,
  memoryHardwareConcurrency: Number,
  memoryUserAgent: String,
  memoryVendor: String,
  memoryVendorSub: String,
  memoryProductSub: String,
  memoryBuildID: String,
  memoryOscpu: String,
  memoryAppCodeName: String,
  memoryAppName: String,
  memoryAppVersion: String,
  memoryLanguageList: [String],
  memoryHardwareConcurrencyCount: Number,
  memoryDevicePixelRatio: Number,
  memoryMaxTouchPointsCount: Number,
  memoryMemoryUsed: Number,
  memoryMemoryTotal: Number,
  memoryMemoryLimit: Number,
  memoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryDeviceMemory: Number,
  memoryMemoryHardwareConcurrency: Number,
  memoryMemoryUserAgent: String,
  memoryMemoryVendor: String,
  memoryMemoryVendorSub: String,
  memoryMemoryProductSub: String,
  memoryMemoryBuildID: String,
  memoryMemoryOscpu: String,
  memoryMemoryAppCodeName: String,
  memoryMemoryAppName: String,
  memoryMemoryAppVersion: String,
  memoryMemoryLanguageList: [String],
  memoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryDevicePixelRatio: Number,
  memoryMemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryUsed: Number,
  memoryMemoryMemoryTotal: Number,
  memoryMemoryMemoryLimit: Number,
  memoryMemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryHardwareConcurrency: Number,
  memoryMemoryMemoryUserAgent: String,
  memoryMemoryMemoryVendor: String,
  memoryMemoryMemoryVendorSub: String,
  memoryMemoryMemoryProductSub: String,
  memoryMemoryMemoryBuildID: String,
  memoryMemoryMemoryOscpu: String,
  memoryMemoryMemoryAppCodeName: String,
  memoryMemoryMemoryAppName: String,
  memoryMemoryMemoryAppVersion: String,
  memoryMemoryMemoryLanguageList: [String],
  memoryMemoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryMemoryUsed: Number,
  memoryMemoryMemoryMemoryTotal: Number,
  memoryMemoryMemoryMemoryLimit: Number,
  memoryMemoryMemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryMemoryHardwareConcurrency: Number,
  memoryMemoryMemoryMemoryUserAgent: String,
  memoryMemoryMemoryMemoryVendor: String,
  memoryMemoryMemoryMemoryVendorSub: String,
  memoryMemoryMemoryMemoryProductSub: String,
  memoryMemoryMemoryMemoryBuildID: String,
  memoryMemoryMemoryMemoryOscpu: String,
  memoryMemoryMemoryMemoryAppCodeName: String,
  memoryMemoryMemoryMemoryAppName: String,
  memoryMemoryMemoryMemoryAppVersion: String,
  memoryMemoryMemoryMemoryLanguageList: [String],
  memoryMemoryMemoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryMemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryMemoryMemoryUsed: Number,
  memoryMemoryMemoryMemoryMemoryTotal: Number,
  memoryMemoryMemoryMemoryMemoryLimit: Number,
  memoryMemoryMemoryMemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryMemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryMemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryMemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryMemoryMemoryHardwareConcurrency: Number,
  memoryMemoryMemoryMemoryMemoryUserAgent: String,
  memoryMemoryMemoryMemoryMemoryVendor: String,
  memoryMemoryMemoryMemoryMemoryVendorSub: String,
  memoryMemoryMemoryMemoryMemoryProductSub: String,
  memoryMemoryMemoryMemoryMemoryBuildID: String,
  memoryMemoryMemoryMemoryMemoryOscpu: String,
  memoryMemoryMemoryMemoryMemoryAppCodeName: String,
  memoryMemoryMemoryMemoryMemoryAppName: String,
  memoryMemoryMemoryMemoryMemoryAppVersion: String,
  memoryMemoryMemoryMemoryMemoryLanguageList: [String],
  memoryMemoryMemoryMemoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryMemoryMemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMemoryMemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryMemoryMemoryMemoryHardwareConcurrency: Number,
  memoryMemoryMemoryMemoryMemoryMemoryUserAgent: String,
  memoryMemoryMemoryMemoryMemoryMemoryVendor: String,
  memoryMemoryMemoryMemoryMemoryMemoryVendorSub: String,
  memoryMemoryMemoryMemoryMemoryMemoryProductSub: String,
  memoryMemoryMemoryMemoryMemoryMemoryBuildID: String,
  memoryMemoryMemoryMemoryMemoryMemoryOscpu: String,
  memoryMemoryMemoryMemoryMemoryMemoryAppCodeName: String,
  memoryMemoryMemoryMemoryMemoryMemoryAppName: String,
  memoryMemoryMemoryMemoryMemoryMemoryAppVersion: String,
  memoryMemoryMemoryMemoryMemoryMemoryLanguageList: [String],
  memoryMemoryMemoryMemoryMemoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryHardwareConcurrency: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryUserAgent: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryVendor: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryVendorSub: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryProductSub: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryBuildID: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryOscpu: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryAppCodeName: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryAppName: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryAppVersion: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryLanguageList: [String],
  memoryMemoryMemoryMemoryMemoryMemoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryHardwareConcurrency: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryUserAgent: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryVendor: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryVendorSub: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryProductSub: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryBuildID: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryOscpu: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryAppCodeName: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryAppName: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryAppVersion: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryLanguageList: [String],
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryHardwareConcurrency: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryUserAgent: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryVendor: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryVendorSub: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryProductSub: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryBuildID: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryOscpu: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryAppCodeName: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryAppName: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryAppVersion: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryLanguageList: [String],
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryHardwareConcurrency: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryUserAgent: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryVendor: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryVendorSub: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryProductSub: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryBuildID: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryOscpu: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryAppCodeName: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryAppName: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryAppVersion: String,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryLanguageList: [String],
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemorymemoryHardwareConcurrency: Number,
  memoryMemoryMemoryMemoryMemoryMemoryMemoryMemorymemoryUserAgent: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryVendor: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryVendorSub: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryProductSub: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryBuildID: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryOscpu: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryAppCodeName: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryAppName: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryAppVersion: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryLanguageList: [String],
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryUsed: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryTotal: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryLimit: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryHardwareConcurrency: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryUserAgent: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryVendor: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryVendorSub: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryProductSub: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryBuildID: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryOscpu: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryAppCodeName: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryAppName: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryAppVersion: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryLanguageList: [String],
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMaxTouchPointsCount: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryUsed: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryTotal: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryLimit: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryJsHeapSizeLimit: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryJsHeapSizeUsed: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryJsHeapSizeTotal: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryDeviceMemory: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryHardwareConcurrency: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryUserAgent: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryVendor: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryVendorSub: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryProductSub: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryBuildID: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryOscpu: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryAppCodeName: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryAppName: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryAppVersion: String,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryLanguageList: [String],
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryHardwareConcurrencyCount: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryDevicePixelRatio: Number,
  memoryMemoryMemoryMemorymemoryMemorymemoryMemorymemoryMemoryMemoryMaxTouchPointsCount: Number
}, { timestamps: true });

// Testimonial Schema
const TestimonialSchema = new Schema({
  name: { type: String, required: true },
  role: { type: String, required: true },
  text: { type: String, required: true },
  image: String,
  rating: { type: Number, min: 1, max: 5, default: 5 },
  approved: { type: Boolean, default: false },
  date: { type: Date, default: Date.now }
}, { timestamps: true });

// Chatbot Conversation Schema
const ChatbotConversationSchema = new Schema({
  userMessage: { type: String, required: true },
  botResponse: { type: String, required: true },
  date: { type: Date, default: Date.now },
  responseTime: Number,
  imageUrl: String,
  isUsefulForTraining: { type: Boolean, default: true }
}, { timestamps: true });

// Models
const LiveNotification = model('LiveNotification', LiveNotificationSchema);
const SiteData = model('SiteData', SiteDataSchema);
const Project = model('Project', ProjectSchema);
const Message = model('Message', MessageSchema);
const Application = model('Application', ApplicationSchema);
const ProjectSubmission = model('ProjectSubmission', ProjectSubmissionSchema);
const User = model('User', UserSchema);
const Visitor = model('Visitor', VisitorSchema);
const Testimonial = model('Testimonial', TestimonialSchema);
const ChatbotConversation = model('ChatbotConversation', ChatbotConversationSchema);
export {
  LiveNotification,
  SiteData,
  Project,
  Message,
  Application,
  ProjectSubmission,
  User,
  Visitor,
  Testimonial,
  ChatbotConversation
};
